### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

### ISSUE THREAD

**Issue by Ecclesiast** [tensorflow/text#385]
Hello!

Could you please help me with this issue? I am using tensorflow image from docker hub `tensorflow==2.3.0`
My Dockerfile looks like this:

![image](https://user-images.githubusercontent.com/24414958/92731601-f7ad1b00-f37d-11ea-9cdd-d9a69af947f2.png)

Locally I installed `tensorflow==2.3.0` and `tensorflow-text==2.3.0` and everything works fine. But when I am using docker image + tensorflow_text I get this issue.

This is my full log:
`File "", line 3, in <module>
    import tensorflow_text
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb`

**Comment by broken** [comment]
This error normally shows when TF is has a separate ABI than the TensorFlow that TF.Text was built against. If in this docker image you reinstall TensorFlow using pip (`pip install -U tensorflow==2.3.0`), do you continue to get this error?

**Comment by Ecclesiast** [comment]
After installing tensorflow==2.3.0 this issue is gone, thank you! 
However, I consider this is a strange logic because I can use container 2.1.0-py3 or 2.3.0 or another container tag and after that install 2.3.0 version. 
Intuitively I don't need to install tf again. Could this be fixed in later versions or should I address this issue somewhere else?

**Comment by broken** [comment]
This is something that should be addressed on TF's side. They are providing you with a binary in this docker image that has a different ABI than what they release publicly. Normally this wouldn't matter, but it does when using libraries that are built to interface with the core TF lib like TF Text.

I expect the docker image did match their build environment at one point, but most likely they updated the build images, but not this other docker image they are providing.  After that, they were providing incompatible versions of their library.

Do you mind creating an issue for TF? We've made a lot of progress working with the team to remove inconsistencies from the build environments, but I hadn't run across this one before, and it would be good for them to see this directly affects users. Thanks.

**Comment by Ecclesiast** [comment]
Thanks for the explanation. Useful to understand.
Yes, I think it's a good idea to create an issue for tensorflow, thanks :+1:

**Comment by mihaimaruseac** [comment]
The docker containers have been republished. Can you check and see if things are working now?

**Comment by IrisDinge** [comment]
@mihaimaruseac 
Nope....
still need do  `pip install -U tensorflow==2.3.0`

**Comment by chunyeow** [comment]
This issue seems not yet resolved with the following error:

`>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 436, in <module>
    _ll.load_library(_main_dir)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 153, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
`

**Comment by puraminy** [comment]
I installed 2.3.0 but error still exists
...
File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_text/__init__.py",
 line 21, in <module>
    from tensorflow_text.python import metrics
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_text/python/metric
s/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_text/python/metric
s/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_t
o_datafile('_text_similarity_metric_ops.so'))
  File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framew
ork/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/pouramini/miniconda3/lib/python
3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined s
ymbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

**Comment by DeathKhan** [comment]
Having same issue but on Arch running on bare metal. Seems to be an issue wtih the numpy version they are training against.

**Comment by puraminy** [comment]
> I installed 2.3.0 but error still exists
> ...
> File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_text/**init**.py",
> line 21, in
> from tensorflow_text.python import metrics
> File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_text/python/metric
> s/**init**.py", line 20, in
> from tensorflow_text.python.metrics.text_similarity_metric_ops import *
> File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_text/python/metric
> s/text_similarity_metric_ops.py", line 28, in
> gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_t
> o_datafile('_text_similarity_metric_ops.so'))
> File "/home/pouramini/miniconda3/lib/python3.7/site-packages/tensorflow_core/python/framew
> ork/load_library.py", line 57, in load_op_library
> lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: /home/pouramini/miniconda3/lib/python
> 3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined s
> ymbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

My problem was resolved. I've read that tensorflow and tensorflow_text must be the same version and particularly I've read they should be version 2.3.0 or probably higher. Moreover, my problem could be due conflicts of `conda` installation and `pip` installation. so, you'd better to install them both with `pip` (cause tensorflow_text) isn't on `conda`) and probably in base environment...

**Comment by xmsec** [comment]
Having same issue and solution above maybe not useful. My problem could be due to tensorflow that was installed with conda. So i try to pip uninstall tensorflow and reinstall it. Then My problem was resolved.

**Comment by Azharazzu** [comment]
this error after installing tf2.3.0
---------------------------------------------------------------------------


NotFoundError                             Traceback (most recent call last)
<ipython-input-2-9495cdc7fbed> in <module>
----> 1 import tensorflow_text as text

~/anaconda3/lib/python3.8/site-packages/tensorflow_text/__init__.py in <module>
     19 # pylint: disable=wildcard-import
     20 from tensorflow_text.python import keras
---> 21 from tensorflow_text.python import metrics
     22 from tensorflow_text.python.ops import *
     23 

~/anaconda3/lib/python3.8/site-packages/tensorflow_text/python/metrics/__init__.py in <module>
     18 
     19 # pylint: disable=wildcard-import
---> 20 from tensorflow_text.python.metrics.text_similarity_metric_ops import *
     21 
     22 # Public symbols in the "tensorflow_text.metrics" package.

~/anaconda3/lib/python3.8/site-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py in <module>
     26 from tensorflow.python.framework import load_library
     27 from tensorflow.python.platform import resource_loader
---> 28 gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
     29 
     30 

~/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     56     RuntimeError: when unable to load the library or get the python wrappers.
     57   """
---> 58   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     59   try:
     60     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /home/cgt_jpr_pc_azhrudin/anaconda3/lib/python3.8/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

**Comment by achbogga** [comment]
Dockerfile needs to be updated ASAP. Why is this issue closed ?

**Comment by dgbaenar** [comment]
I just pulled and ran the image, and the problem is stills present.

**Comment by broken** [comment]
I ran across this issue while searching for something else. It's quite old, so I'm not sure if this affects anybody currently, but if you have a similar problem, please create a new issue. Closed issues are not monitored, so you will not get a response replying to closed issues like this one.

Related, TF and TF Text have transitioned builds & tests to using new publicly available docker images beginning with v2.9. There is more information on the images [here](https://www.tensorflow.org/install/docker), and we will separately be updating our documentation on how to run tests and builds with these images soon.

**Comment by haooooooqi** [comment]
wondering if we have a solution here

**Comment by DaddyWesker** [comment]
I'm having this issue with 2.11 and 2.12 installed from pip. I'm out of solutions here.

**Comment by manikanta5557** [comment]
> I'm having this issue with 2.11 and 2.12 installed from pip. I'm out of solutions here. Though 2.5 works fine. But i need latest. Linux Mint 20.1

I am having the same issue with tensorflow 2.6 - 2.13. is your issue solved?
